# AQUO

```{r setupAquo}
require(tidyverse)
require(data.table)
require(rwsapi)
require(rlist)
require(stringr)
require(aquodom)
# Lees functie in voor download domeintabellen
source("c:/git_checkouts/Accessing-MediaWiki-Aquo-Code-Examples/ExampleCodeRStudio/GetDomainTable.R")
# source_url("https://github.com/Aquo-standaard/Accessing-MediaWiki-Aquo-Code-Examples/blob/main/ExampleCodeRStudio/GetDomainTable.R")

ddlmetadata <- rws_metadata() 
metadataLijst <- ddlmetadata$content$AquoMetadataLijst %>%
  list.flatten() %>% as.data.frame(stringsAsFactors = F)

KwaliteitswaardecodeLijst <- tibble(kwaliteitswaardecode = ddlmetadata$content$KwaliteitswaardecodeLijst)
ReferentievlakLijst <- tibble(kwaliteitswaardecode = ddlmetadata$content$ReferentievlakLijst)


```


AQUO is de nederlandse standaard voor watergerelateerde data. Voor uitwisseling van meetgegevens is er het informatiemodel IM-AQUO. Dit model 

## Relevante AQUO vocabulaires (domeintabellen)





```{r}
dom_overzicht(peildatum = Sys.Date())
dom("Eenheid")
# lijkt niet te werken. Morgen nog eens proberen, anders aan Koos of Johan vragen. 
# 
```


## Gebruik van AQUO in RWS datadistributielaag


